/**
 * Built-in starter templates shown in the Template Library alongside any
 * workspace library entries served by GET /templates/library.
 */

export interface StarterTemplate {
  id: string;
  name: string;
  technicalName: string;
  category: "marketing" | "utility" | "authentication";
  subcategory: string;
  headline?: string;
  body: string;
  footer?: string;
  headerType?: "IMAGE" | "TEXT" | "VIDEO" | "DOCUMENT";
  buttonText?: string;
  buttonType?: "URL" | "QUICK_REPLY";
  language: string;
  componentsCount: number;
}

export const STARTER_TEMPLATES: StarterTemplate[] = [
  // ================= NONPROFIT (5) =================
  {
    id: "np-1",
    name: "nonprofit fundraising campaign",
    technicalName: "nonprofit_fundraising_campaign",
    category: "marketing",
    subcategory: "nonprofit",
    body: "Hi {{1}}, support our {{2}} campaign and help us reach more people in need. Every contribution matters.",
    footer: "Together, we can make a difference.",
    headerType: "IMAGE",
    buttonText: "Donate Now",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "np-2",
    name: "nonprofit campaigns carousel",
    technicalName: "nonprofit_campaigns_carousel",
    category: "marketing",
    subcategory: "nonprofit",
    body: "Hi {{1}}, choose a cause you care about and support our active campaigns.",
    footer: "Building brighter futures.",
    headerType: "IMAGE",
    buttonText: "Explore Causes",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "np-3",
    name: "nonprofit donation receipt",
    technicalName: "nonprofit_donation_receipt",
    category: "utility",
    subcategory: "nonprofit",
    body: "Hi {{1}}, your donation receipt for contribution ID {{2}} is ready. Please download it from the link below.",
    footer: "Tax exemption certificate 80G included.",
    headerType: "DOCUMENT",
    buttonText: "Download Receipt",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "np-4",
    name: "nonprofit volunteer drive invite",
    technicalName: "nonprofit_volunteer_drive_invite",
    category: "marketing",
    subcategory: "nonprofit",
    body: "Hi {{1}}, join our volunteer drive on {{2}} at {{3}}. Your time can make a real difference.",
    footer: "Make an impact in your community.",
    headerType: "IMAGE",
    buttonText: "Register as Volunteer",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "np-5",
    name: "nonprofit donation thank you",
    technicalName: "nonprofit_donation_thank_you",
    category: "utility",
    subcategory: "nonprofit",
    headline: "Thank You for Donating",
    body: "Hi {{1}}, thank you for your generous donation of ₹{{2}}. Your support helps us serve our community.",
    footer: "With sincere gratitude from our entire team.",
    headerType: "TEXT",
    buttonText: "View Impact Report",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },

  // ================= HEALTHCARE (5) =================
  {
    id: "hc-1",
    name: "healthcare appointment confirmation",
    technicalName: "healthcare_appointment_confirmation",
    category: "utility",
    subcategory: "healthcare",
    headline: "Appointment Confirmed",
    body: "Hi {{1}}, your appointment with Dr. {{2}} is confirmed for {{3}} at {{4}}.",
    footer: "Please arrive 10 minutes before your slot.",
    headerType: "TEXT",
    buttonText: "View Clinic Location",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "hc-2",
    name: "healthcare medicine reminder",
    technicalName: "healthcare_medicine_reminder",
    category: "utility",
    subcategory: "healthcare",
    headline: "Medicine Reminder",
    body: "Hi {{1}}, this is a reminder to take your prescribed medicine {{2}} at {{3}}.",
    footer: "Stay healthy and adhere to your prescription.",
    headerType: "TEXT",
    buttonText: "I have taken it",
    buttonType: "QUICK_REPLY",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "hc-3",
    name: "healthcare lab report ready",
    technicalName: "healthcare_lab_report_ready",
    category: "utility",
    subcategory: "healthcare",
    body: "Hi {{1}}, your lab report for {{2}} is now available. Please consult your doctor for medical advice.",
    footer: "Diagnostic Care Centre",
    headerType: "DOCUMENT",
    buttonText: "Download Lab Report",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "hc-4",
    name: "healthcare services carousel",
    technicalName: "healthcare_services_carousel",
    category: "marketing",
    subcategory: "healthcare",
    body: "Hi {{1}}, explore our healthcare services designed for your well-being.",
    footer: "Comprehensive care for your family.",
    headerType: "IMAGE",
    buttonText: "Book Checkup",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "hc-5",
    name: "healthcare wellness checkup discount",
    technicalName: "healthcare_wellness_checkup_discount",
    category: "marketing",
    subcategory: "healthcare",
    body: "Hi {{1}}, get 30% off on full body health packages this month. Use code {{2}} at checkout.",
    footer: "Offer valid till end of month.",
    headerType: "IMAGE",
    buttonText: "Claim Discount",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },

  // ================= WEBINAR (5) =================
  {
    id: "wb-1",
    name: "webinar invitation growth masterclass",
    technicalName: "webinar_invitation_growth_masterclass",
    category: "marketing",
    subcategory: "webinar",
    body: "Hi {{1}}, join our live webinar on {{2}} and learn practical strategies from industry experts. Seats are limited.",
    footer: "Live Q&A included.",
    headerType: "IMAGE",
    buttonText: "Reserve Free Seat",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "wb-2",
    name: "webinar registration confirmation",
    technicalName: "webinar_registration_confirmation",
    category: "utility",
    subcategory: "webinar",
    headline: "Registration Confirmed",
    body: "Hi {{1}}, your registration for {{2}} is confirmed. The session starts on {{3}} at {{4}}.",
    footer: "Link to join will be active 15 mins prior.",
    headerType: "TEXT",
    buttonText: "Add to Calendar",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "wb-3",
    name: "webinar reminder one hour",
    technicalName: "webinar_reminder_one_hour",
    category: "utility",
    subcategory: "webinar",
    headline: "Webinar Starts Soon",
    body: "Hi {{1}}, reminder that {{2}} starts in 1 hour. Keep your questions ready for the live Q&A.",
    footer: "See you in the session!",
    headerType: "TEXT",
    buttonText: "Join Stream Now",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "wb-4",
    name: "webinar recording available",
    technicalName: "webinar_recording_available",
    category: "utility",
    subcategory: "webinar",
    body: "Hi {{1}}, thanks for attending {{2}}. The recording is now available for you to watch anytime.",
    footer: "Access available for 30 days.",
    headerType: "VIDEO",
    buttonText: "Watch Recording",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "wb-5",
    name: "webinar series carousel",
    technicalName: "webinar_series_carousel",
    category: "marketing",
    subcategory: "webinar",
    body: "Hi {{1}}, explore our upcoming webinar series and choose the session that fits your goals.",
    footer: "Master new skills weekly.",
    headerType: "IMAGE",
    buttonText: "View Schedule",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },

  // ================= ECOMMERCE (5) =================
  {
    id: "ec-1",
    name: "ecommerce order confirmation",
    technicalName: "ecommerce_order_confirmation",
    category: "utility",
    subcategory: "ecommerce",
    headline: "Order Confirmed",
    body: "Hi {{1}}, your order #{{2}} for {{3}} has been confirmed and is being packed.",
    footer: "Track delivery status in real-time.",
    headerType: "TEXT",
    buttonText: "Track Order",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "ec-2",
    name: "ecommerce shipping update",
    technicalName: "ecommerce_shipping_update",
    category: "utility",
    subcategory: "ecommerce",
    headline: "Out for Delivery",
    body: "Hi {{1}}, your package is out for delivery with courier partner {{2}}. Delivery OTP is {{3}}.",
    footer: "Expected delivery by 6 PM today.",
    headerType: "TEXT",
    buttonText: "Live GPS Tracking",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "ec-3",
    name: "ecommerce abandoned cart discount",
    technicalName: "ecommerce_abandoned_cart_discount",
    category: "marketing",
    subcategory: "ecommerce",
    body: "Hi {{1}}, items in your cart are waiting! Complete your order now and enjoy 15% off with code {{2}}.",
    footer: "Cart reserved for 24 hours.",
    headerType: "IMAGE",
    buttonText: "Complete Purchase",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "ec-4",
    name: "ecommerce product back in stock",
    technicalName: "ecommerce_product_back_in_stock",
    category: "marketing",
    subcategory: "ecommerce",
    body: "Good news {{1}}! The item {{2}} you were looking for is back in stock. Grab yours before it runs out.",
    footer: "Limited quantities available.",
    headerType: "IMAGE",
    buttonText: "Buy Now",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "ec-5",
    name: "ecommerce festive flash sale",
    technicalName: "ecommerce_festive_flash_sale",
    category: "marketing",
    subcategory: "ecommerce",
    body: "Hi {{1}}, our biggest festive sale is live! Get up to 50% discount on entire {{2}} collection today.",
    footer: "Free shipping on orders above ₹499.",
    headerType: "IMAGE",
    buttonText: "Shop Collection",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },

  // ================= EDUCATION (5) =================
  {
    id: "ed-1",
    name: "education course enrollment confirmation",
    technicalName: "education_course_enrollment_confirmation",
    category: "utility",
    subcategory: "education",
    headline: "Welcome to Class",
    body: "Hi {{1}}, you are successfully enrolled in {{2}}. Your portal credentials have been sent to {{3}}.",
    footer: "Class starts next Monday.",
    headerType: "TEXT",
    buttonText: "Access Student Portal",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "ed-2",
    name: "education exam schedule announcement",
    technicalName: "education_exam_schedule_announcement",
    category: "utility",
    subcategory: "education",
    body: "Dear {{1}}, the exam schedule for semester {{2}} has been published. Please review your hall ticket details.",
    footer: "Controller of Examinations",
    headerType: "DOCUMENT",
    buttonText: "Download Hall Ticket",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "ed-3",
    name: "education new batch scholarship offer",
    technicalName: "education_new_batch_scholarship_offer",
    category: "marketing",
    subcategory: "education",
    body: "Hi {{1}}, applications for {{2}} merit scholarship are now open. Get up to 100% tuition waiver.",
    footer: "Limited seats. Apply before the deadline.",
    headerType: "IMAGE",
    buttonText: "Apply for Scholarship",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "ed-4",
    name: "education webinar masterclass invite",
    technicalName: "education_webinar_masterclass_invite",
    category: "marketing",
    subcategory: "education",
    body: "Hi {{1}}, join our career masterclass on {{2}} with senior instructors from top tech institutes.",
    footer: "Includes certificate of participation.",
    headerType: "IMAGE",
    buttonText: "Register Free",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "ed-5",
    name: "education fee payment receipt",
    technicalName: "education_fee_payment_receipt",
    category: "utility",
    subcategory: "education",
    headline: "Payment Received",
    body: "Hi {{1}}, we received fee payment of ₹{{2}} for student ID {{3}}. Transaction ref: {{4}}.",
    footer: "Official fee acknowledgment.",
    headerType: "TEXT",
    buttonText: "Download Receipt",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },

  // ================= BANKING (5) =================
  {
    id: "bk-1",
    name: "banking transaction alert",
    technicalName: "banking_transaction_alert",
    category: "utility",
    subcategory: "banking",
    headline: "Transaction Alert",
    body: "A/C *{{1}} debited with ₹{{2}} on {{3}}. Available balance is ₹{{4}}.",
    footer: "If not done by you, block card instantly.",
    headerType: "TEXT",
    buttonText: "Report Dispute",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "bk-2",
    name: "banking otp verification",
    technicalName: "banking_otp_verification",
    category: "authentication",
    subcategory: "banking",
    headline: "Your verification code",
    body: "{{1}} is your one-time password (OTP) for login verification. Valid for 10 minutes. Do not share with anyone.",
    footer: "Security Verification",
    headerType: "TEXT",
    buttonText: "Copy OTP Code",
    buttonType: "QUICK_REPLY",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "bk-3",
    name: "banking loan pre approval offer",
    technicalName: "banking_loan_pre_approval_offer",
    category: "marketing",
    subcategory: "banking",
    body: "Congratulations {{1}}! You have pre-approved personal loan offer of up to ₹{{2}} with zero paperwork.",
    footer: "Interest rate starting 10.49% p.a.",
    headerType: "IMAGE",
    buttonText: "Check Loan Limit",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "bk-4",
    name: "banking monthly statement ready",
    technicalName: "banking_monthly_statement_ready",
    category: "utility",
    subcategory: "banking",
    body: "Dear {{1}}, your e-statement for account *{{2}} for the month of {{3}} is now available for download.",
    footer: "Password is your 4-digit birth year + PAN.",
    headerType: "DOCUMENT",
    buttonText: "View Statement",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "bk-5",
    name: "banking credit card reward points",
    technicalName: "banking_credit_card_reward_points",
    category: "marketing",
    subcategory: "banking",
    body: "Hi {{1}}, you have {{2}} unredeemed credit card reward points expiring on {{3}}. Convert to vouchers today.",
    footer: "Redeem against shopping and flights.",
    headerType: "IMAGE",
    buttonText: "Redeem Points",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },

  // ================= AUTOMOBILE (5) =================
  {
    id: "au-1",
    name: "automobile test drive booking confirmation",
    technicalName: "automobile_test_drive_booking_confirmation",
    category: "utility",
    subcategory: "automobile",
    headline: "Test Drive Confirmed",
    body: "Hi {{1}}, your test drive for {{2}} is confirmed at {{3}} dealership on {{4}}.",
    footer: "Please carry valid driving license.",
    headerType: "TEXT",
    buttonText: "Directions to Showroom",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "au-2",
    name: "automobile service maintenance reminder",
    technicalName: "automobile_service_maintenance_reminder",
    category: "utility",
    subcategory: "automobile",
    headline: "Service Due",
    body: "Hi {{1}}, your vehicle {{2}} is due for periodic maintenance service. Book doorstep pick & drop.",
    footer: "Ensure optimal vehicle performance.",
    headerType: "TEXT",
    buttonText: "Schedule Service Slot",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "au-3",
    name: "automobile vehicle inspection report",
    technicalName: "automobile_vehicle_inspection_report",
    category: "utility",
    subcategory: "automobile",
    body: "Hi {{1}}, the multi-point inspection report for your vehicle {{2}} is ready with diagnostic results.",
    footer: "Authorized Service Center",
    headerType: "DOCUMENT",
    buttonText: "Download Full Report",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "au-4",
    name: "automobile new car launch event",
    technicalName: "automobile_new_car_launch_event",
    category: "marketing",
    subcategory: "automobile",
    body: "Hi {{1}}, experience the all-new {{2}} with futuristic electric powertrain and ADAS level 2 safety.",
    footer: "Special pre-booking benefits available.",
    headerType: "IMAGE",
    buttonText: "Explore Features",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "au-5",
    name: "automobile festive exchange bonus",
    technicalName: "automobile_festive_exchange_bonus",
    category: "marketing",
    subcategory: "automobile",
    body: "Upgrade your drive {{1}}! Get additional exchange bonus of up to ₹{{2}} when trading in old vehicle.",
    footer: "Free valuation at your doorstep.",
    headerType: "IMAGE",
    buttonText: "Get Free Valuation",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },

  // ================= REAL-ESTATE (5) =================
  {
    id: "re-1",
    name: "real-estate site visit confirmation",
    technicalName: "real_estate_site_visit_confirmation",
    category: "utility",
    subcategory: "real-estate",
    headline: "Site Visit Confirmed",
    body: "Hi {{1}}, your visit to {{2}} project is confirmed for {{3}}. Relationship manager {{4}} will guide you.",
    footer: "Complimentary cab facility arranged.",
    headerType: "TEXT",
    buttonText: "Open Location Map",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "re-2",
    name: "real-estate property booking token receipt",
    technicalName: "real_estate_booking_token_receipt",
    category: "utility",
    subcategory: "real-estate",
    body: "Dear {{1}}, we acknowledge receipt of booking token for unit #{{2}} in {{3}}. Welcome to the community.",
    footer: "Official Developer Booking Slip",
    headerType: "DOCUMENT",
    buttonText: "Download Receipt",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "re-3",
    name: "real-estate exclusive penthouse launch",
    technicalName: "real_estate_exclusive_penthouse_launch",
    category: "marketing",
    subcategory: "real-estate",
    body: "Hi {{1}}, presenting ultra-luxury 4 & 5 BHK sky villas at {{2}} with private deck and panoramic city views.",
    footer: "Early bird pricing for VIP clients.",
    headerType: "IMAGE",
    buttonText: "Download Brochure",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "re-4",
    name: "real-estate investment opportunities brochure",
    technicalName: "real_estate_investment_opportunities",
    category: "marketing",
    subcategory: "real-estate",
    body: "Hi {{1}}, discover high-yielding commercial real estate assets with assured {{2}}% rental returns.",
    footer: "Grade A pre-leased office spaces.",
    headerType: "IMAGE",
    buttonText: "View ROI Calculator",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "re-5",
    name: "real-estate price drop alert",
    technicalName: "real_estate_price_drop_alert",
    category: "marketing",
    subcategory: "real-estate",
    body: "Price Drop Alert {{1}}! The 3 BHK apartment in {{2}} is now available at revised pricing with zero GST.",
    footer: "Only 2 units remaining at this price.",
    headerType: "IMAGE",
    buttonText: "Book Inspection",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },

  // ================= SERVICE (5) =================
  {
    id: "sv-1",
    name: "service subscription renewal offer",
    technicalName: "service_subscription_renewal_offer",
    category: "marketing",
    subcategory: "service",
    body: "Hi {{1}}, renew your {{2}} subscription today and get a special discount using the coupon code below.",
    footer: "Never miss out on premium features.",
    headerType: "IMAGE",
    buttonText: "Renew with 20% Off",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "sv-2",
    name: "service technician visit scheduled",
    technicalName: "service_technician_visit_scheduled",
    category: "utility",
    subcategory: "service",
    headline: "Technician Assigned",
    body: "Hi {{1}}, engineer {{2}} is assigned for your service request #{{3}} and will arrive on {{4}}.",
    footer: "Call helpline for rescheduling.",
    headerType: "TEXT",
    buttonText: "Track Technician Live",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "sv-3",
    name: "service request resolved feedback",
    technicalName: "service_request_resolved_feedback",
    category: "utility",
    subcategory: "service",
    headline: "Service Completed",
    body: "Hi {{1}}, ticket #{{2}} has been resolved. Please take 10 seconds to rate your service experience.",
    footer: "Your feedback helps us improve.",
    headerType: "TEXT",
    buttonText: "Rate Experience",
    buttonType: "QUICK_REPLY",
    language: "EN_US",
    componentsCount: 3,
  },
  {
    id: "sv-4",
    name: "service annual maintenance contract promo",
    technicalName: "service_annual_maintenance_contract_promo",
    category: "marketing",
    subcategory: "service",
    body: "Hi {{1}}, safeguard your appliances with AMC plans covering unlimited breakdowns and free spares.",
    footer: "Complete peace of mind coverage.",
    headerType: "IMAGE",
    buttonText: "Choose AMC Plan",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
  {
    id: "sv-5",
    name: "service invoice receipt ready",
    technicalName: "service_invoice_receipt_ready",
    category: "utility",
    subcategory: "service",
    body: "Hi {{1}}, invoice #{{2}} for ₹{{3}} has been generated for your recent service on {{4}}.",
    footer: "GST Tax Invoice Attached",
    headerType: "DOCUMENT",
    buttonText: "Download Invoice PDF",
    buttonType: "URL",
    language: "EN_US",
    componentsCount: 4,
  },
];
